### PR TITLE
Reduction in binary size, access time.

### PR DESCRIPTION
**Pull request by wbrickner**
I have not profiled startup time, it's tricky because it only occurs once per run of the executable.
Left as an exercise for the reader :)

On my machine the amortized access times have been reduced to `142ns`.
That's pretty good, and better than `std` containers like `BTreeMap`.

Further improvements:
  - compressed representation can be made smaller, `gzip -9` gives better results than using `libflate` in the build script. Go figure.
  - load time can probably be improved by using mostly stack-allocated buffers for words.

Hopefully everything looks good to you.

### CODE REVIEW

**Review by grantshandy — APPROVED** [review]
Looks great! Thank you so much for your expert work on this :)

**Comment by grantshandy** [comment]
Thanks this is a really cool pull request, it's just got one problem.

Build scripts aren't supposed to modify the source directory so we've got to find a way for it to compress the gzip file into the target directory or just give the crate to the user with the gzip file directly included, otherwise I won't be able to put it on crates.io.

**Comment by wbrickner** [comment]
Oh! I had no idea. I think it works to just move this to the root directory rather than the `src` directory? Does that still count as a violation?

**Comment by grantshandy** [comment]
Yeah, I think it does, it has to be inside of the target directory.

Should we just get rid of the build script and directly include the .gz file?

**Comment by wbrickner** [comment]
The benefit of the build script is that when the dictionary gets improved / updated the gzip version automatically gets updated.

I can change the build script to write to the target directory.

**Comment by grantshandy** [comment]
Okay sure that sounds good.

**Comment by grantshandy** [comment]
Okay, I just fixed it, thanks for your wonderful work :)

**Pull request merged**
